RFC: Optional `rich-click` integration (#1745)
* RFC: Optional `rich-cli` integration

* chore: update lock file

* fix: expose fd/uds & correct rich-click printing

* fix: updated tests

* fix: updated test cases

* fix: test cases

* fix: correct random not callable error:

Traceback (most recent call last):
  File "/home/oracle/Code/Starlite/litestar/.venv/bin/litestar", line 6, in <module>
    sys.exit(__main__())
             ^^^^^^^^^^
TypeError: 'module' object is not callabl

* fix: styling modification

* fix: add cover hint

* Apply suggestions from code review

Co-authored-by: Na'aman Hirschfeld <nhirschfeld@gmail.com>

* fix: use TYPE_CHECKING to handle linting errors instead of using ignores

* fix: remove additional ignores

* fix: adds a note about `rich-click` dependency

* Update litestar/cli/_utils.py

Co-authored-by: Janek Nouvertné <25355197+provinzkraut@users.noreply.github.com>

* fix: lint ignores

* fix: updated to address comments.

* fix: updated ignores

* Update litestar/cli/_utils.py

Co-authored-by: Janek Nouvertné <25355197+provinzkraut@users.noreply.github.com>

* Apply suggestions from code review

Co-authored-by: Janek Nouvertné <25355197+provinzkraut@users.noreply.github.com>

* fix: formatting

* fix: typo correction

* fix: variable name

---------

Co-authored-by: Na'aman Hirschfeld <nhirschfeld@gmail.com>
Co-authored-by: Janek Nouvertné <25355197+provinzkraut@users.noreply.github.com>